# Generated by Django 5.2.3 on 2025-06-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('10:00-10:30', '10:00 AM - 10:30 AM'), ('10:30-11:00', '10:30 AM - 11:00 AM'), ('11:00-11:30', '11:00 AM - 11:30 AM'), ('11:30-12:00', '11:30 AM - 12:00 PM'), ('12:00-12:30', '12:00 PM - 12:30 PM'), ('12:30-13:00', '12:30 PM - 1:00 PM'), ('14:00-14:30', '2:00 PM - 2:30 PM'), ('14:30-15:00', '2:30 PM - 3:00 PM'), ('15:00-15:30', '3:00 PM - 3:30 PM'), ('15:30-16:00', '3:30 PM - 4:00 PM'), ('16:00-16:30', '4:00 PM - 4:30 PM'), ('16:30-17:00', '4:30 PM - 5:00 PM')], max_length=15),
        ),
    ]
